"""30 diverse fictional seed scenarios for EU Small Claims statistics."""

SEED_SCENARIOS = [
    # ── 1. Starker Fall: Warenlieferung DE→DE, alle Beweise, gewonnen ──
    {
        "title": "Müller GmbH vs. Fischer OHG — Warenlieferung Elektronikteile",
        "claim_type": "invoice",
        "cl_name": "Müller Elektronik GmbH",
        "cl_country": "DE",
        "def_name": "Fischer Handels OHG",
        "def_country": "DE",
        "court_country": "DE",
        "amount": 2500.0,
        "description": "Lieferung von Elektronikbauteilen gemäß Kaufvertrag vom 01.02.2025. Ware am 15.02.2025 geliefert und angenommen. Rechnung Nr. 2025-0198 über EUR 2.500 war am 01.04.2025 fällig. Trotz Mahnung erfolgte keine Zahlung.",
        "evidence_desc": "Kaufvertrag, Auftragsbestätigung, Lieferschein mit Empfangsbestätigung, Rechnung Nr. 2025-0198, Mahnung mit Fristsetzung",
        "p_recht": 0.95,
        "p_beweis": 0.92,
        "p_eintreibung": 0.85,
        "outcome": "won",
        "assessment": "Starke Beweislage: schriftlicher Vertrag, Liefernachweis, dokumentierte Mahnung. Hohe Erfolgswahrscheinlichkeit.",
        "events": ["FILED", "SERVICE_OK", "DEFAULT", "JUDGMENT_WIN", "PAYMENT_RECEIVED"],
        "is_cross_border": False,
    },
    # ── 2. Schwacher Fall: Mündlicher Vertrag DE→DE, kaum Beweise, verloren ──
    {
        "title": "Schneider vs. Braun — Mündlicher Dienstleistungsvertrag",
        "claim_type": "werklohn",
        "cl_name": "Hans Schneider",
        "cl_country": "DE",
        "def_name": "Karl Braun",
        "def_country": "DE",
        "court_country": "DE",
        "amount": 800.0,
        "description": "Mündlich vereinbarte Gartenarbeiten im März 2025. Kein schriftlicher Vertrag. Arbeiten wurden erbracht, jedoch keine Dokumentation der Leistung vorhanden.",
        "evidence_desc": "Keine schriftlichen Nachweise, nur eigene Aussage",
        "p_recht": 0.45,
        "p_beweis": 0.15,
        "p_eintreibung": None,
        "outcome": "lost",
        "assessment": "Schwache Beweislage: nur mündliche Vereinbarung, keine Dokumentation. Geringe Erfolgsaussichten.",
        "events": ["FILED", "SERVICE_OK", "DEFENDANT_RESPONDED", "JUDGMENT_LOSS"],
        "is_cross_border": False,
    },
    # ── 3. Vergleich: Qualitätsstreit DE→IT, mittlere Beweislage ──
    {
        "title": "Weber GmbH vs. Rossi S.r.l. — Qualitätsstreit Textilien",
        "claim_type": "invoice",
        "cl_name": "Weber Mode GmbH",
        "cl_country": "DE",
        "def_name": "Rossi Tessuti S.r.l.",
        "def_country": "IT",
        "court_country": "DE",
        "amount": 3000.0,
        "description": "Lieferung von Textilien gemäß Vertrag. Beklagter beanstandet die Qualität und verweigert Zahlung. Klägerin bestreitet Mängel.",
        "evidence_desc": "Kaufvertrag, Lieferschein, Qualitätszertifikat, Reklamationsschreiben des Beklagten",
        "p_recht": 0.68,
        "p_beweis": 0.60,
        "p_eintreibung": 0.75,
        "outcome": "settled",
        "assessment": "Streitfall mit Qualitätsdispute. Vergleich erzielt: EUR 2.400 (80% der Forderung).",
        "events": ["FILED", "SERVICE_OK", "DEFENDANT_RESPONDED", "SETTLED", "PAYMENT_RECEIVED"],
        "is_cross_border": True,
    },
    # ── 4. Insolvenz: Starke Beweise, Beklagter insolvent DE→CZ ──
    {
        "title": "Becker e.K. vs. Novak s.r.o. — Zahlungsausfall wegen Insolvenz",
        "claim_type": "invoice",
        "cl_name": "Thomas Becker e.K.",
        "cl_country": "DE",
        "def_name": "Novak Strojírenství s.r.o.",
        "def_country": "CZ",
        "court_country": "DE",
        "amount": 4500.0,
        "description": "Lieferung von IT-Ausstattung an Beklagte. Vollständige Dokumentation vorhanden. Beklagte hat Insolvenz angemeldet.",
        "evidence_desc": "Kaufvertrag, Auftragsbestätigung, Lieferschein, Rechnung, zwei Mahnungen, Insolvenzbekanntmachung",
        "p_recht": 0.90,
        "p_beweis": 0.85,
        "p_eintreibung": 0.05,
        "outcome": "lost",
        "assessment": "Starke Beweislage, aber Beklagter insolvent. Urteil gewonnen, Vollstreckung gescheitert.",
        "events": ["FILED", "SERVICE_OK", "DEFAULT", "JUDGMENT_WIN", "COLLECTION_FAILED"],
        "is_cross_border": True,
    },
    # ── 5. BENUTZER-BEISPIEL: Schadenersatz AT→DE, Trauerschaden Auto, Schlüssigkeit 0% ──
    {
        "title": "Huber vs. Krause — Schadenersatz Trauerschaden Autounfall",
        "claim_type": "damages",
        "cl_name": "Maria Huber",
        "cl_country": "AT",
        "def_name": "Fritz Krause",
        "def_country": "DE",
        "court_country": "AT",
        "amount": 4800.0,
        "description": "Klägerin fordert Trauerschaden wegen Blechschaden an ihrem Auto durch den Beklagten. Im ESCP-Verfahren ist ein Trauerschaden für Sachschäden am Fahrzeug rechtlich nicht begründbar — es handelt sich um immateriellen Schaden, der im Bagatellverfahren nicht zugesprochen wird.",
        "evidence_desc": "Polizeibericht, Fotos vom Blechschaden, Werkstattrechnung, ärztliches Attest über psychische Belastung",
        "p_recht": 0.0,
        "p_beweis": 0.70,
        "p_eintreibung": None,
        "outcome": "lost",
        "assessment": "Klage unschlüssig: Trauerschaden für Sachbeschädigung ist im ESCP nicht vorgesehen. p_recht = 0%. Klage als unschlüssig zurückgewiesen.",
        "events": ["FILED", "SERVICE_OK", "DEFENDANT_RESPONDED", "JUDGMENT_LOSS"],
        "is_cross_border": True,
    },
    # ── 6. Grenzüberschreitend DE→FR, Versäumnisurteil, erfolgreich ──
    {
        "title": "Schmidt IT GmbH vs. Dupont SARL — IT-Dienstleistungen",
        "claim_type": "werklohn",
        "cl_name": "Schmidt IT Solutions GmbH",
        "cl_country": "DE",
        "def_name": "Dupont Digital SARL",
        "def_country": "FR",
        "court_country": "DE",
        "amount": 1200.0,
        "description": "Remote-IT-Support und Systemwartung für die Beklagte im Zeitraum Januar bis März 2025. Beklagte reagierte nicht auf Rechnungen und Mahnungen.",
        "evidence_desc": "Dienstleistungsvertrag, Stundennachweise, Rechnung, zwei Mahnungen per Einschreiben",
        "p_recht": 0.82,
        "p_beweis": 0.75,
        "p_eintreibung": 0.80,
        "outcome": "won",
        "assessment": "Grenzüberschreitend DE→FR. Versäumnisurteil nach ausbleibender Reaktion. Vollstreckung in Frankreich erfolgreich.",
        "events": ["FILED", "SERVICE_OK", "DEFAULT", "JUDGMENT_WIN", "PAYMENT_RECEIVED"],
        "is_cross_border": True,
    },
    # ── 7. Zustellung gescheitert: Falsche Adresse ES→PT ──
    {
        "title": "García S.L. vs. Silva Lda. — Zustellungsfehler",
        "claim_type": "invoice",
        "cl_name": "García Importaciones S.L.",
        "cl_country": "ES",
        "def_name": "Silva Comércio Lda.",
        "def_country": "PT",
        "court_country": "ES",
        "amount": 1800.0,
        "description": "Lieferung von Olivenöl. Beklagte ist unter angegebener Adresse nicht erreichbar. Zustellung gescheitert.",
        "evidence_desc": "Kaufvertrag, Rechnung, Lieferschein, Zustellungsversuchsprotokoll",
        "p_recht": 0.75,
        "p_beweis": 0.65,
        "p_eintreibung": None,
        "outcome": "withdrawn",
        "assessment": "Zustellung am Sitz des Beklagten gescheitert. Verfahren eingestellt.",
        "events": ["FILED", "SERVICE_FAIL"],
        "is_cross_border": True,
    },
    # ── 8. Verjährung: Forderung zu alt NL→BE ──
    {
        "title": "van der Berg B.V. vs. Janssens BVBA — Verjährte Forderung",
        "claim_type": "invoice",
        "cl_name": "van der Berg Handel B.V.",
        "cl_country": "NL",
        "def_name": "Janssens Trading BVBA",
        "def_country": "BE",
        "court_country": "NL",
        "amount": 2200.0,
        "description": "Warenlieferung aus dem Jahr 2019. Forderung wurde erst 2025 eingeklagt. Der Beklagte beruft sich auf die dreijährige Verjährungsfrist nach belgischem Recht.",
        "evidence_desc": "Alter Kaufvertrag von 2019, Rechnung, Lieferschein, keine Verjährungshemmung nachweisbar",
        "p_recht": 0.10,
        "p_beweis": 0.80,
        "p_eintreibung": None,
        "outcome": "lost",
        "assessment": "Forderung verjährt. Trotz guter Beweislage keine Durchsetzbarkeit wegen Verjährungseinrede.",
        "events": ["FILED", "SERVICE_OK", "DEFENDANT_RESPONDED", "JUDGMENT_LOSS"],
        "is_cross_border": True,
    },
    # ── 9. Rückforderung: Doppelzahlung PL→DE ──
    {
        "title": "Kowalski Sp. z o.o. vs. Hoffmann GmbH — Doppelzahlung",
        "claim_type": "refund",
        "cl_name": "Kowalski Logistik Sp. z o.o.",
        "cl_country": "PL",
        "def_name": "Hoffmann Maschinenbau GmbH",
        "def_country": "DE",
        "court_country": "DE",
        "amount": 3500.0,
        "description": "Versehentliche Doppelüberweisung von EUR 3.500. Beklagte verweigert Rückzahlung und behauptet, die Zahlung sei für eine andere offene Rechnung.",
        "evidence_desc": "Zwei Banküberweisungsbelege, Kontoauszüge, Korrespondenz, ursprüngliche Rechnung",
        "p_recht": 0.78,
        "p_beweis": 0.72,
        "p_eintreibung": 0.88,
        "outcome": "won",
        "assessment": "Doppelzahlung nachweisbar durch Bankbelege. Beklagte konnte keine offene Forderung belegen.",
        "events": ["FILED", "SERVICE_OK", "DEFENDANT_RESPONDED", "JUDGMENT_WIN", "PAYMENT_RECEIVED"],
        "is_cross_border": True,
    },
    # ── 10. BENUTZER-BEISPIEL: Warenlieferung LV→EE, kein Vertrag, kein Beweis ──
    {
        "title": "Bērziņš SIA vs. Tamm OÜ — Warenlieferung ohne Vertrag",
        "claim_type": "invoice",
        "cl_name": "Bērziņš Trading SIA",
        "cl_country": "LV",
        "def_name": "Tamm Kaubandus OÜ",
        "def_country": "EE",
        "court_country": "LV",
        "amount": 1500.0,
        "description": "Kläger behauptet Warenlieferung an Beklagten. Kein schriftlicher Vertrag vorhanden, keine Rechnung, kein Lieferschein. Nur mündliche Behauptungen.",
        "evidence_desc": "Keine Beweismittel. Kein Vertrag, keine Rechnung, kein Lieferschein, keine Korrespondenz.",
        "p_recht": 1.0,
        "p_beweis": 0.0,
        "p_eintreibung": None,
        "outcome": "lost",
        "assessment": "Anspruch schlüssig vorgetragen (p_recht=100%), aber keinerlei Beweismittel (p_beweis=0%). Klage wegen Beweislosigkeit abgewiesen.",
        "events": ["FILED", "SERVICE_OK", "DEFENDANT_RESPONDED", "JUDGMENT_LOSS"],
        "is_cross_border": True,
    },
    # ── 11. Falscher Beklagter: Klage gegen falsche Person AT→AT ──
    {
        "title": "Steiner KG vs. Maier Consulting — Falscher Beklagter",
        "claim_type": "werklohn",
        "cl_name": "Steiner Bau KG",
        "cl_country": "AT",
        "def_name": "Maier Consulting e.U.",
        "def_country": "AT",
        "court_country": "AT",
        "amount": 2800.0,
        "description": "Klägerin fordert Werkvertragsvergütung. Der Vertrag wurde jedoch mit der Maier GmbH geschlossen, nicht mit der Maier Consulting e.U. — falscher Beklagter.",
        "evidence_desc": "Werkvertrag mit Maier GmbH (nicht Maier Consulting), Rechnungen, Korrespondenz",
        "p_recht": 0.0,
        "p_beweis": 0.60,
        "p_eintreibung": None,
        "outcome": "lost",
        "assessment": "Passivlegitimation fehlt: Vertrag wurde mit anderer Rechtsperson geschlossen. Klage als unschlüssig abgewiesen.",
        "events": ["FILED", "SERVICE_OK", "DEFENDANT_RESPONDED", "JUDGMENT_LOSS"],
        "is_cross_border": False,
    },
    # ── 12. Ungerechtfertigte Bereicherung: Fehlüberweisung FI→SE ──
    {
        "title": "Virtanen Oy vs. Eriksson AB — Fehlüberweisung",
        "claim_type": "unjust_enrichment",
        "cl_name": "Virtanen Tuonti Oy",
        "cl_country": "FI",
        "def_name": "Eriksson Handel AB",
        "def_country": "SE",
        "court_country": "FI",
        "amount": 4200.0,
        "description": "Irrtümliche Banküberweisung an falschen Empfänger. Beklagter erkennt Zahlung an, verweigert aber Rückzahlung.",
        "evidence_desc": "Überweisungsbeleg, Bankbestätigung, Korrespondenz mit Beklagtem, der Empfang bestätigt",
        "p_recht": 0.92,
        "p_beweis": 0.90,
        "p_eintreibung": 0.82,
        "outcome": "won",
        "assessment": "Klarer Fall ungerechtfertigter Bereicherung. Beklagter hat Empfang bestätigt.",
        "events": ["FILED", "SERVICE_OK", "DEFAULT", "JUDGMENT_WIN", "PAYMENT_RECEIVED"],
        "is_cross_border": True,
    },
    # ── 13. Zuständigkeitsproblem: Falsche Zuständigkeit DK→IE ──
    {
        "title": "Jensen ApS vs. O'Brien Ltd — Zuständigkeitsstreit",
        "claim_type": "invoice",
        "cl_name": "Jensen Møbler ApS",
        "cl_country": "DK",
        "def_name": "O'Brien Interiors Ltd",
        "def_country": "IE",
        "court_country": "DK",
        "amount": 3800.0,
        "description": "Möbellieferung nach Irland. Beklagter rügt die internationale Zuständigkeit des dänischen Gerichts. Erfüllungsort war Dublin.",
        "evidence_desc": "Kaufvertrag mit Erfüllungsort Dublin, Lieferschein nach Dublin",
        "p_recht": 0.15,
        "p_beweis": 0.70,
        "p_eintreibung": None,
        "outcome": "lost",
        "assessment": "Zuständigkeitsrüge erfolgreich: Erfüllungsort Dublin, dänisches Gericht unzuständig.",
        "events": ["FILED", "SERVICE_OK", "DEFENDANT_RESPONDED", "JUDGMENT_LOSS"],
        "is_cross_border": True,
    },
    # ── 14. Sehr klarer Fall: Rechnung mit Mahnung IT→IT ──
    {
        "title": "Bianchi S.r.l. vs. Romano S.p.A. — Unbezahlte Rechnung",
        "claim_type": "invoice",
        "cl_name": "Bianchi Forniture S.r.l.",
        "cl_country": "IT",
        "def_name": "Romano Costruzioni S.p.A.",
        "def_country": "IT",
        "court_country": "IT",
        "amount": 4900.0,
        "description": "Lieferung von Baumaterialien. Schriftlicher Vertrag, Lieferung bestätigt, Rechnung anerkannt, aber nicht bezahlt. Drei Mahnungen ignoriert.",
        "evidence_desc": "Kaufvertrag, Bestellschein, Lieferschein, Empfangsbestätigung, Rechnung, drei Mahnungen",
        "p_recht": 0.98,
        "p_beweis": 0.95,
        "p_eintreibung": 0.90,
        "outcome": "won",
        "assessment": "Perfekte Beweislage. Versäumnisurteil, sofortige Zahlung.",
        "events": ["FILED", "SERVICE_OK", "DEFAULT", "JUDGMENT_WIN", "PAYMENT_RECEIVED"],
        "is_cross_border": False,
    },
    # ── 15. Mangel-Einrede: Werkvertrag mit Mängeln HU→SK ──
    {
        "title": "Nagy Kft. vs. Horváth s.r.o. — Werkvertrag mit Mängelrüge",
        "claim_type": "werklohn",
        "cl_name": "Nagy Építő Kft.",
        "cl_country": "HU",
        "def_name": "Horváth Stavby s.r.o.",
        "def_country": "SK",
        "court_country": "HU",
        "amount": 3200.0,
        "description": "Renovierungsarbeiten durchgeführt. Beklagter rügt Mängel und verweigert Restzahlung. Sachverständigengutachten bestätigt teilweise Mängel.",
        "evidence_desc": "Werkvertrag, Fotos, Sachverständigengutachten, Abnahmeprotokoll mit Mängelhinweis",
        "p_recht": 0.55,
        "p_beweis": 0.50,
        "p_eintreibung": 0.70,
        "outcome": "settled",
        "assessment": "Teilmängel bestätigt. Vergleich über 65% der Forderung.",
        "events": ["FILED", "SERVICE_OK", "DEFENDANT_RESPONDED", "SETTLED", "PAYMENT_RECEIVED"],
        "is_cross_border": True,
    },
    # ── 16. Kein Rechtsgrund: Sonstige Forderung ohne Grundlage RO→BG ──
    {
        "title": "Popescu S.R.L. vs. Ivanov EOOD — Unbegründete Forderung",
        "claim_type": "other",
        "cl_name": "Popescu Trading S.R.L.",
        "cl_country": "RO",
        "def_name": "Ivanov Commerce EOOD",
        "def_country": "BG",
        "court_country": "RO",
        "amount": 1100.0,
        "description": "Kläger fordert Schadensersatz wegen angeblich entgangener Geschäftsmöglichkeit. Kein Vertrag, keine vertragliche Beziehung nachweisbar.",
        "evidence_desc": "E-Mail-Korrespondenz über mögliche Zusammenarbeit, die nie zustande kam",
        "p_recht": 0.0,
        "p_beweis": 0.20,
        "p_eintreibung": None,
        "outcome": "lost",
        "assessment": "Kein Rechtsgrund: Es bestand kein Vertrag und keine Verpflichtung. Klage unschlüssig.",
        "events": ["FILED", "SERVICE_OK", "DEFENDANT_RESPONDED", "JUDGMENT_LOSS"],
        "is_cross_border": True,
    },
    # ── 17. B2C-Fall: Verbraucher gegen Online-Shop HR→SI ──
    {
        "title": "Kovačević vs. Horvat d.o.o. — Online-Bestellung nicht geliefert",
        "claim_type": "refund",
        "cl_name": "Ana Kovačević",
        "cl_country": "HR",
        "def_name": "Horvat Spletna Trgovina d.o.o.",
        "def_country": "SI",
        "court_country": "HR",
        "amount": 350.0,
        "description": "Online-Bestellung von Möbeln bezahlt, aber nie geliefert. Shop reagiert nicht auf Anfragen und Beschwerden.",
        "evidence_desc": "Bestellbestätigung, Zahlungsbeleg PayPal, E-Mails ohne Antwort, Screenshots der Webseite",
        "p_recht": 0.88,
        "p_beweis": 0.82,
        "p_eintreibung": 0.60,
        "outcome": "won",
        "assessment": "Verbraucher-Fall: Zahlung nachgewiesen, Lieferung nicht erfolgt. Versäumnisurteil.",
        "events": ["FILED", "SERVICE_OK", "DEFAULT", "JUDGMENT_WIN", "PAYMENT_RECEIVED"],
        "is_cross_border": True,
    },
    # ── 18. Hoher Betrag, gute Beweise, Vollstreckung gescheitert EL→CY ──
    {
        "title": "Papadopoulos A.E. vs. Christou Ltd — Vollstreckung auf Zypern",
        "claim_type": "invoice",
        "cl_name": "Papadopoulos Emporiki A.E.",
        "cl_country": "EL",
        "def_name": "Christou Trading Ltd",
        "def_country": "CY",
        "court_country": "EL",
        "amount": 4800.0,
        "description": "Lieferung von Lebensmitteln nach Zypern. Urteil gewonnen, aber Vollstreckung auf Zypern gescheitert — Firma aufgelöst.",
        "evidence_desc": "Kaufvertrag, Zollpapiere, Lieferschein, Rechnung, Mahnungen",
        "p_recht": 0.85,
        "p_beweis": 0.80,
        "p_eintreibung": 0.03,
        "outcome": "lost",
        "assessment": "Gute Erfolgsaussichten, aber Firma zwischenzeitlich aufgelöst. Vollstreckung unmöglich.",
        "events": ["FILED", "SERVICE_OK", "DEFAULT", "JUDGMENT_WIN", "COLLECTION_FAILED"],
        "is_cross_border": True,
    },
    # ── 19. Teilzahlung bereits erfolgt, Restforderung LT→LV ──
    {
        "title": "Kazlauskas UAB vs. Liepiņš SIA — Restforderung Maschinenbau",
        "claim_type": "invoice",
        "cl_name": "Kazlauskas Statyba UAB",
        "cl_country": "LT",
        "def_name": "Liepiņš Mašīnbūve SIA",
        "def_country": "LV",
        "court_country": "LT",
        "amount": 1900.0,
        "description": "Maschinenteile geliefert. Beklagter hat EUR 2.100 von EUR 4.000 gezahlt, Restbetrag EUR 1.900 steht aus. Beklagter behauptet Mängelminderung.",
        "evidence_desc": "Kaufvertrag, Teilzahlungsnachweis, Rechnung über Gesamtbetrag, Mängelrüge des Beklagten",
        "p_recht": 0.65,
        "p_beweis": 0.55,
        "p_eintreibung": 0.72,
        "outcome": "settled",
        "assessment": "Vergleich: EUR 1.400 (74% der Restforderung) als Einmalbetrag.",
        "events": ["FILED", "SERVICE_OK", "DEFENDANT_RESPONDED", "SETTLED", "PAYMENT_RECEIVED"],
        "is_cross_border": True,
    },
    # ── 20. Zurückgezogen: Parteien einigen sich vor Verhandlung MT→MT ──
    {
        "title": "Camilleri vs. Borg — Außergerichtliche Einigung",
        "claim_type": "werklohn",
        "cl_name": "Joseph Camilleri",
        "cl_country": "MT",
        "def_name": "Mark Borg",
        "def_country": "MT",
        "court_country": "MT",
        "amount": 950.0,
        "description": "Malerarbeiten. Parteien einigen sich nach Klageeinreichung außergerichtlich, Klage wird zurückgenommen.",
        "evidence_desc": "Kostenvoranschlag, WhatsApp-Nachrichten, Fotos der Arbeiten",
        "p_recht": 0.70,
        "p_beweis": 0.55,
        "p_eintreibung": 0.65,
        "outcome": "withdrawn",
        "assessment": "Klage zurückgezogen nach außergerichtlicher Einigung.",
        "events": ["FILED"],
        "is_cross_border": False,
    },
    # ── 21. Schadenersatz: Transportschaden BE→NL ──
    {
        "title": "Peeters BVBA vs. de Vries B.V. — Transportschaden",
        "claim_type": "damages",
        "cl_name": "Peeters Logistics BVBA",
        "cl_country": "BE",
        "def_name": "de Vries Transport B.V.",
        "def_country": "NL",
        "court_country": "BE",
        "amount": 2700.0,
        "description": "Transportschaden an Maschinenteilen während des Transports von Belgien in die Niederlande. Beklagter bestreitet Verantwortung.",
        "evidence_desc": "CMR-Frachtbrief, Schadensprotokoll, Fotos, Versicherungsgutachten, Haftungsklausel im Vertrag",
        "p_recht": 0.72,
        "p_beweis": 0.68,
        "p_eintreibung": 0.85,
        "outcome": "won",
        "assessment": "Haftung des Frachtführers gemäß CMR nachgewiesen.",
        "events": ["FILED", "SERVICE_OK", "DEFENDANT_RESPONDED", "JUDGMENT_WIN", "PAYMENT_RECEIVED"],
        "is_cross_border": True,
    },
    # ── 22. Alles exzellent: Perfekter Fall LU→LU ──
    {
        "title": "Schmit S.à r.l. vs. Muller S.A. — Klarer Zahlungsverzug",
        "claim_type": "invoice",
        "cl_name": "Schmit Électronique S.à r.l.",
        "cl_country": "LU",
        "def_name": "Muller Industries S.A.",
        "def_country": "LU",
        "court_country": "LU",
        "amount": 3400.0,
        "description": "Warenlieferung mit schriftlichem Vertrag, Empfangsbestätigung, unbezahlte Rechnung. Beklagter hat Forderung schriftlich anerkannt.",
        "evidence_desc": "Kaufvertrag, Lieferschein, Empfangsbestätigung, Rechnung, Forderungsanerkenntnis per E-Mail",
        "p_recht": 0.99,
        "p_beweis": 0.98,
        "p_eintreibung": 0.92,
        "outcome": "won",
        "assessment": "Perfekter Fall: Forderung anerkannt, alle Beweise vorhanden. Sofortige Zahlung nach Versäumnisurteil.",
        "events": ["FILED", "SERVICE_OK", "DEFAULT", "JUDGMENT_WIN", "PAYMENT_RECEIVED"],
        "is_cross_border": False,
    },
    # ── 23. Zurückgezogen wegen Zustellungsproblem PL→CZ ──
    {
        "title": "Wiśniewski Sp. z o.o. vs. Černý s.r.o. — Zustellung gescheitert",
        "claim_type": "invoice",
        "cl_name": "Wiśniewski Meble Sp. z o.o.",
        "cl_country": "PL",
        "def_name": "Černý Nábytek s.r.o.",
        "def_country": "CZ",
        "court_country": "PL",
        "amount": 2100.0,
        "description": "Möbellieferung. Beklagte Firma unter Geschäftsadresse nicht auffindbar. Zustellung mehrfach gescheitert.",
        "evidence_desc": "Kaufvertrag, Lieferschein, Rechnung, zwei gescheiterte Zustellungsversuche",
        "p_recht": 0.80,
        "p_beweis": 0.70,
        "p_eintreibung": None,
        "outcome": "withdrawn",
        "assessment": "Verfahren eingestellt wegen gescheiterter Zustellung.",
        "events": ["FILED", "SERVICE_FAIL"],
        "is_cross_border": True,
    },
    # ── 24. Aufrechnung: Gegenforderung übersteigt Klage FR→FR ──
    {
        "title": "Leroy SARL vs. Martin SAS — Aufrechnung mit Gegenforderung",
        "claim_type": "invoice",
        "cl_name": "Leroy Construction SARL",
        "cl_country": "FR",
        "def_name": "Martin Matériaux SAS",
        "def_country": "FR",
        "court_country": "FR",
        "amount": 1600.0,
        "description": "Warenlieferung von Baumaterialien. Beklagter rechnet mit Gegenforderung wegen früherer mangelhafter Lieferung auf.",
        "evidence_desc": "Kaufvertrag, Rechnung, Lieferschein, Gegenforderung des Beklagten mit Mängelrüge und Sachverständigengutachten",
        "p_recht": 0.40,
        "p_beweis": 0.55,
        "p_eintreibung": 0.80,
        "outcome": "lost",
        "assessment": "Aufrechnung mit begründeter Gegenforderung. Klage abgewiesen.",
        "events": ["FILED", "SERVICE_OK", "DEFENDANT_RESPONDED", "JUDGMENT_LOSS"],
        "is_cross_border": False,
    },
    # ── 25. Starker B2C-Fall: Defektes Produkt SE→DE ──
    {
        "title": "Lindström vs. TechShop GmbH — Defektes Elektronikgerät",
        "claim_type": "refund",
        "cl_name": "Erik Lindström",
        "cl_country": "SE",
        "def_name": "TechShop Online GmbH",
        "def_country": "DE",
        "court_country": "SE",
        "amount": 890.0,
        "description": "Online bestelltes Elektronikgerät (Laptop) ist defekt angekommen. Rücksendung verweigert durch den Shop.",
        "evidence_desc": "Bestellbestätigung, Zahlungsnachweis, Fotos des defekten Geräts, E-Mail-Korrespondenz mit Rücksendeanfrage",
        "p_recht": 0.90,
        "p_beweis": 0.85,
        "p_eintreibung": 0.78,
        "outcome": "won",
        "assessment": "Verbraucherrecht: Defektes Produkt, Rückerstattungspflicht klar. Versäumnisurteil.",
        "events": ["FILED", "SERVICE_OK", "DEFAULT", "JUDGMENT_WIN", "PAYMENT_RECEIVED"],
        "is_cross_border": True,
    },
    # ── 26. Kein Anspruch: ESCP nicht anwendbar (> 5000 EUR) reduziert ──
    {
        "title": "Dubois SARL vs. Klein GmbH — Ingenieurleistungen",
        "claim_type": "werklohn",
        "cl_name": "Dubois Ingénierie SARL",
        "cl_country": "FR",
        "def_name": "Klein Maschinenbau GmbH",
        "def_country": "DE",
        "court_country": "FR",
        "amount": 4950.0,
        "description": "Ingenieurdienstleistungen erbracht. Beklagter bestreitet Umfang der vereinbarten Leistungen. Vertrag unklar formuliert.",
        "evidence_desc": "Vertragsentwurf (nicht unterschrieben), E-Mail-Verkehr, Stundenzettel (teilweise unleserlich)",
        "p_recht": 0.50,
        "p_beweis": 0.35,
        "p_eintreibung": 0.75,
        "outcome": "lost",
        "assessment": "Vertrag unklar, Leistungsumfang nicht nachweisbar. Klage abgewiesen.",
        "events": ["FILED", "SERVICE_OK", "DEFENDANT_RESPONDED", "JUDGMENT_LOSS"],
        "is_cross_border": True,
    },
    # ── 27. Vollstreckung in anderem Land: DE→IT, Inkasso schwierig ──
    {
        "title": "Wagner GmbH vs. Conti S.r.l. — Schwierige Vollstreckung in Italien",
        "claim_type": "invoice",
        "cl_name": "Wagner Werkzeuge GmbH",
        "cl_country": "DE",
        "def_name": "Conti Meccanica S.r.l.",
        "def_country": "IT",
        "court_country": "DE",
        "amount": 3900.0,
        "description": "Werkzeuglieferung nach Italien. Urteil erhalten, aber Vollstreckung in Italien dauert Monate und scheitert an fehlenden Vermögenswerten.",
        "evidence_desc": "Kaufvertrag, Lieferschein, Rechnung, Mahnungen, Vollstreckungsversuchsprotokoll",
        "p_recht": 0.88,
        "p_beweis": 0.82,
        "p_eintreibung": 0.10,
        "outcome": "lost",
        "assessment": "Urteil gewonnen, aber Vollstreckung in Italien gescheitert — keine pfändbaren Vermögenswerte.",
        "events": ["FILED", "SERVICE_OK", "DEFAULT", "JUDGMENT_WIN", "COLLECTION_FAILED"],
        "is_cross_border": True,
    },
    # ── 28. Erfolgreicher Vergleich: Softwarelizenz PT→ES ──
    {
        "title": "Santos Lda. vs. López S.L. — Softwarelizenz",
        "claim_type": "werklohn",
        "cl_name": "Santos Software Lda.",
        "cl_country": "PT",
        "def_name": "López Digital S.L.",
        "def_country": "ES",
        "court_country": "PT",
        "amount": 2600.0,
        "description": "Softwareentwicklung und Lizenzgebühren. Beklagter nutzt Software weiter, zahlt aber nicht. Vergleich nach Klageeinreichung.",
        "evidence_desc": "Lizenzvertrag, Login-Protokolle als Nutzungsnachweis, Rechnungen, E-Mail-Korrespondenz",
        "p_recht": 0.75,
        "p_beweis": 0.70,
        "p_eintreibung": 0.80,
        "outcome": "settled",
        "assessment": "Vergleich: EUR 2.200 in drei Raten.",
        "events": ["FILED", "SERVICE_OK", "DEFENDANT_RESPONDED", "SETTLED", "PAYMENT_RECEIVED"],
        "is_cross_border": True,
    },
    # ── 29. Kein Beweis, kein Recht: Totaler Nullfall BG→RO ──
    {
        "title": "Dimitrov EOOD vs. Ionescu S.R.L. — Völlig haltlose Klage",
        "claim_type": "damages",
        "cl_name": "Dimitrov Konsult EOOD",
        "cl_country": "BG",
        "def_name": "Ionescu Retail S.R.L.",
        "def_country": "RO",
        "court_country": "BG",
        "amount": 2000.0,
        "description": "Kläger behauptet Schaden durch angebliche Wettbewerbsverletzung. Kein Wettbewerbsverbot vereinbart, keine vertragliche Beziehung, kein Schaden nachweisbar.",
        "evidence_desc": "Keine relevanten Beweismittel. Screenshots der Webseite des Beklagten.",
        "p_recht": 0.0,
        "p_beweis": 0.05,
        "p_eintreibung": None,
        "outcome": "lost",
        "assessment": "Völlig unbegründete Klage: kein Rechtsgrund, keine Beweise. Sofort abgewiesen.",
        "events": ["FILED", "SERVICE_OK", "DEFENDANT_RESPONDED", "JUDGMENT_LOSS"],
        "is_cross_border": True,
    },
    # ── 30. Grenzüberschreitend mit hohem EV: NL→DE, gute Vollstreckung ──
    {
        "title": "Bakker B.V. vs. Lehmann GmbH — Blumen-Großhandel",
        "claim_type": "invoice",
        "cl_name": "Bakker Bloemen B.V.",
        "cl_country": "NL",
        "def_name": "Lehmann Floristik GmbH",
        "def_country": "DE",
        "court_country": "NL",
        "amount": 4100.0,
        "description": "Regelmäßige Blumenlieferungen über drei Monate. Letzte drei Rechnungen unbezahlt. Vollständige Vertragsdokumentation.",
        "evidence_desc": "Rahmenvertrag, Einzelbestellungen, Lieferscheine, drei Rechnungen, zwei Mahnungen",
        "p_recht": 0.93,
        "p_beweis": 0.90,
        "p_eintreibung": 0.88,
        "outcome": "won",
        "assessment": "Klarer Fall: Rahmenvertrag, nachgewiesene Lieferungen, unbezahlte Rechnungen. Vollstreckung in DE erfolgreich.",
        "events": ["FILED", "SERVICE_OK", "DEFAULT", "JUDGMENT_WIN", "PAYMENT_RECEIVED"],
        "is_cross_border": True,
    },
]
